### ISSUE TITLE
[ADD] 공통 버튼(하단 빨간 버튼) UIComponent에 생성

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#11]
## 💡 Issue

공통 버튼을 UIComponent에 따로 생성합니다.

## 📝  todo
- [x] MainButton 생성
- [x] 활성화, 비활성화 적용
- [x] 내부 text 변경 적용
- [x] shadow 거는 경우 잡기
- [x] width, height 잡기
