### ISSUE TITLE
[CHORE] 메인 화면 스타일 변경

### ISSUE THREAD

**Issue by coby5502** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#110]
## 📝  todo
- [x] CreateRoomCollectionViewCell, ManitoRoomCollectionCell 색깔 및 투명도 변경
- [x] SafeArea 무시하고 배경 꽉 채우기
- [x] 마니또 이미지 밑으로 좀 더 내리기
