### ISSUE TITLE
[FEAT] DetailEditView 취소 시 alert표시

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#115]
## 💡 Issue

- DetailEditView의 기능들을 수정합니다

## 📝  todo
- [ ] 모달 내릴시 or 취소시 alert표시
- [ ] 날짜를 변경하지 않으면 변경버튼 비활성화
- [ ] 기간 재설정 alert의 확인을 눌러서 view로 이동했을 땐 인원설정 표시 x
