### ISSUE TITLE
[FEAT] DetailEditView modal 수정

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#119]
## 💡 Issue

DetailEditView 모달에 대한 나머지 사항들을 수정합니다.

## 📝  todo
- [x] 변경이 하나라도 있으면 변경이 활성화 아니면 비활성화상태
- [x]  인원수정 isHidden 처리하기
- [x]  진행 기간 눌렀을때 변경 모달 뜨도록
- [x]  슬라이더 확인^__^
