### ISSUE TITLE
[CHORE] 전체 아이콘 도트 변경하기

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#140]
## 💡 Issue

아이콘을 도트로 변경합니다.

## 📝  todo
- [x] 뒤로 가기 버튼 변경
- [x] x 버튼 도트로 변경
- [x] 설정 버튼 도트로 변경
- [x] 공유하기 버튼 도트로 변경
- [x] 사진 버튼 도트로 변경
- [x] 신고하기 도트 추가
- [x] information 도트 추가
