### ISSUE TITLE
[FEAT] 방 참가하기 플로우에서 뷰 디자인 수정

### ISSUE THREAD

**Issue by coby5502** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#189]
## 💡 Issue

방 참가하기 플로우에서 뷰 디자인 수정
## 📝  todo
- [ ] 캐릭터 Cell 따로 만들기
- [ ] 캐릭터 선택뷰, 선택 기능 되도록 수정
- [ ] 네비게이션 바 디자인 수정
