### ISSUE TITLE
[ADD] CreateRoom UI구현

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#2]
## 💡 Issue

CreateRoom 생성하기 UI구현

## 📝  todo
- [x] todo !

- [x] 방 생성하기 타이틀 UI
- [x] 방 이름 적는 텍스트필드 UI
- [x] 방 이름 글자 수 제한 라벨
- [x] 다음 버튼 UI
- [x] 참여 인원 라벨
- [x] 참여 인원 슬라이더바
- [x] 참여 인원 바
- [x] 활동기간 라벨

**Comment by MMMIIIN** [comment]
호야 화이팅 !
