### ISSUE TITLE
[FEAT] 쪽지 창 UI 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#209]
## 💡 Issue

쪽지 창에서 쪽지들이 보이도록 UI를 구현합니다.

## 📝  todo
- [x] 보낸 쪽지들 가져오기
- [x] 받은 쪽지들 가져오기
- [x] 쪽지 보내고 나서 reload되도록 변경
- [x] 방 id 연결
- [x] 마니띠 id, 방 id 보내기
