### ISSUE TITLE
[ADD] 디테일 진행중 완료 UI구현

### ISSUE THREAD

**Issue by sunchoi22** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#34]
## 💡 Issue

디테일 진행중 완료된 마니또 방 UI구현합니다.

## 📝  todo
- [x] 개별미션에 아웃라인 색상 변경하기
- [x] 진행정보에 함께 했던 기록 버튼 구현하기
- [x] 마니또 공개버튼 미션 진행여부에 따라 보이고 안보이도록 구현하기
