### ISSUE TITLE
[FEAT] 카톡 링크를 통해서 초대 코드 붙여 넣는 기능 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#348]
## 💡 Issue

초대 코드 복사 > 카톡에서 복붙을 했을 때 > 초대 코드 + 앱으로 오는 링크가 생김 > 링크 클릭 > 초대코드 화면으로 이동

<img width="570" alt="스크린샷 2022-11-15 오후 2 19 22" src="https://user-images.githubusercontent.com/55099365/201832702-da532209-2160-466e-8366-afbbb75f22c6.png">

## 📝  todo
- [ ] 초대 코드 복사 시에 앱 연결 링크 생성
- [ ] 앱 연결 링크를 통해서 앱에 진입하기 구현
- [ ] 앱에 진입했을 때 원하는 뷰로 이동하도록 구현
- [ ] 초대 코드가 clipboard에 보이도록 구현
- [ ] 앱이 없을 시에 app store로 이동하도록 구현
