### ISSUE TITLE
[FEAT] 방 생성하기 뷰 기능 구현

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#35]
## 💡 Issue

- 방 생성하기 뷰 기능 구현

## 📝  todo
- [x] todo !

- [x] Input 방 이름 뷰 기능 구현.
- [x] Input 인원 수 뷰 기능 구현
- [x] 다음 버튼 누를시 다음 뷰 연결
- [x] 뷰 변경 애니메이션 넣기
