### ISSUE TITLE
[CHORE] LetterViewController를 컨벤션에 맞춰서 코드 수정

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#370]
## 💡 Issue

LetterViewController 내부 코드를 컨벤션에 맞춰서 수정합니다.

## 📝  todo
- [x] Letter ViewController들 수정
- [ ] Letter 내부 Cell 파일 수정
- [ ] Letter 내부 UIComponent 파일 수정
