### ISSUE TITLE
[REFACTOR] CreateLetterViewController에서 Model, View 분리 진행

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#391]
## 💡 Issue

CreateLetterViewController에서 Model, View 분리를 진행합니다.
Model를 처리하기 위해서 ViewModel같은 역할을 하는 파일을 따로 만들 수도 있을 것 같습니다.

## 📝  todo
- [ ] View 분리 진행 -> CreateLetterView
- [ ] TextView, PhotoView 수정
- [ ] Model 분리 진행
