### ISSUE TITLE
[REFACTOR] Guide View를 UIView로 분리 진행

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#400]
## 💡 Issue

Guide View가 현재 BaseViewController의 내부에 들어가 있습니다. 이를 분리합니다.

## 📝  todo
- [ ] GuideView 생성
- [ ] UIViewController에 상속 시키기
- [ ] Main에 잘 뜨는지 확인
- [ ] Detail-ing에 잘 뜨는지 확인
- [ ] Letter에 잘 뜨는지 확인
