### ISSUE TITLE
[FEAT] 쪽지 작성 기능 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#41]
## 💡 Issue

쪽지를 작성하는 기능을 추가합니다.

## 📝  todo
- [x] 쪽지 Content 추가
- [x] 사진 content 추가
- [x] 둘 중 하나만 들어와도 보내기 버튼 활성화
- [x] 변경 사항이 있는 경우 구현
- [x] 취소 버튼 dismiss 구현
- [ ] 코드 전체 정리

**Comment by MMMIIIN** [comment]
디너 짱
