### ISSUE TITLE
[CHORE] Interaction 부분 코드 컨벤션 수정

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#426]
## 💡 Issue

Interaction 내부 코드를 수정합니다.

## 📝  todo
- [x] OpenManittoViewController 컨벤션 수정
- [x] OpenManittoPopupViewController 컨벤션 수정
- [x] SelectManittoViewController 컨벤션 수정
- [x] ManittoCollectionViewCell 컨벤션 수정
