### ISSUE TITLE
[DEL] 사용하지 않는 Interaction 스토리보드 제거 및 Interaction 스토리보드에 있던 UI Component를 코드로 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#428]
## 💡 Issue

- Interaction 스토리보드에 있던 UI Component를 코드로 구현
- 사용하지 않는 Interaction 스토리보드 제거

## 📝  todo
- [x] OpenManittoPopupVC 스토리보드 삭제
- [x] SelectManittoVC 내부 UI Component 코드로 구현
- [x] SelectManittoVC 스토리보드 삭제
