### ISSUE TITLE
[ADD] 함께 했던 기록 UI구현

### ISSUE THREAD

**Issue by sunchoi22** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#43]
## 💡 Issue
마니띠, 마니또와의 추억 UI를 구현합니다.

## 📝  todo
- [x] 상단 네비게이션 바 구현
- [x] 마니띠, 마니또와의 추억 버튼 구현
- [x] 추억 내용과 구현
