### ISSUE TITLE
[REFACTOR] MVVM 패턴 형식으로 Letter 스크린 부분 리팩토링

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#465]
## 💡 Issue

Letter Screen를 MVVM 패턴 형식으로 리팩토링합니다.

## 📝  todo
- [x] 도메인 모델 작성
- [x] Service, ViewModel 코드 분리
- [x] ViewController 코드 수정
- [x] ViewModel, ViewController 연결 진행
