### ISSUE TITLE
[FEAT] Build Configuration 분리 작업 진행

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#484]
## 💡 Issue

Build 시 Configuration를 분리하는 작업을 진행합니다.

## 📝  todo
- [ ] Configuration 생성
- [ ] Configuration마다 다른 서버 URL 가지도록 수정
- [ ] Google.plist 분리해서 추가
- [ ] build phrase 작성
