### ISSUE TITLE
[FEAT] Network 모듈 생성 및 Network 라이브러리 적용

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#490]
## 💡 Issue

Network 모듈을 생성하고, Network 라이브러리를 적용해서 코드를 수정합니다.

## 📝  todo
- [ ] Network 모듈 생성
- [ ] Network 라이브러리 적용
- [ ] Network 코드 수정
