### ISSUE TITLE
[ADD] Main UI 구현

### ISSUE THREAD

**Issue by coby5502** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#5]
## 💡 Issue

메인화면 UI 구현
## 📝  todo

- [x] 상단 바
- [x] 공통 미션 터미널
- [x] 마니또 목록 박스
- [x] 마니또 생성 박스
- [x] 마니또 생성 Sheet

**Comment by dangsal** [comment]
요롷게!

**Comment by MMMIIIN** [comment]
코비 화이팅 !
