### ISSUE TITLE
[MOVE] Error, UIComponent, Resource 폴더를 이동시킵니다.

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#518]
## 💡 Issue

Error, UIComponent, Resource 폴더를 Global에서 이동시킵니다.

## 📝  todo
- [x] Error를 Presentation 내부로 이동
- [x] UIComponent를 Common 내부로 이동
- [x] Resource 밖으로 빼기
