### ISSUE TITLE
[CHORE] Extension 폴더 내부 파일들 수정

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#524]
## 💡 Issue

Extension 폴더 내부에 있는 파일들 중에서 필요하지 않은 내용을 지우고 메서드를 수정합니다.

## 📝  todo
- [x] setTyping, applyColor를 VC 내부로 메서드 이동
- [x] Date 관련 함수 수정
- [x] UIButton 부분 확인
