### ISSUE TITLE
[FEAT] Resource, Literal 파일 정리

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#530]
## 💡 Issue

Resource, Literal 파일을 정리합니다.

## 📝  todo
- [x] Resource 파일 위치 수정
- [x] Font 파일 이동
~- [ ] Color Asset 생성~
~- [ ] SwiftGen으로 Color 파일 재생성~
- [x] Googlesheet로 정리 후 Literal 재생성
- [ ] TextLiteral로 작성
