### ISSUE TITLE
[FEAT] Mail 관련 Extension을 따로 관리하는 Service 타입 생성

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#556]
## 💡 Issue

메일 관련 부분이 중복적으로 나타나서 이를 관리하는 Service 타입을 따로 생성해볼까 합니다.

## 📝  todo
- [ ] Service 타입 생성
- [ ] Letter 부분 수정(신고하기)
- [ ] Setting 부분 수정(문의하기)
