### ISSUE TITLE
[REFACTOR] SelectManitteeVC 리팩토링 진행

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#566]
## 💡 Issue

SelectManitteeVC를 MVVM 패턴으로 리팩토링 합니다.

## 📝  todo
- [x] ViewModel에서 type 설정하도록 수정
- [x] ViewModel로부터 manittee 받기
- [x] ViewModel로부터 roomId 받기
