### ISSUE TITLE
[REFACTOR] FriendListVC 리팩토링 진행 및 스토리보드 제거

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#571]
## 💡 Issue

FriendListVC를 리팩토링합니다. 스토리보드를 제거합니다.

## 📝  todo
- [x] 스토리 보드 제거
- [x] FriendListVC 내부 코드 리팩토링 - Usecase, ViewModel
- [x] FriendList View에서 CompositionalLayout 사용
