### ISSUE TITLE
[ADD] 쪽지함 뷰 레이아웃 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#6]
## 💡 Issue

쪽지함 뷰 전체적인 레이아웃을 구현합니다.

## 📝  todo
- [ ] 상단 네비게이션 바 구현
- [ ] 쪽지 쓰기 버튼 구현
- [ ] Segment Control 설정
- [ ] 쪽지함 타이틀 구현
- [ ] CollectionView 자리잡기
