### ISSUE TITLE
[FEAT] 의존성 주입(DI) 코드 관리를 위한 클래스 추가

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#608]
## 💡 Issue

ViewController 간 의존성 주입을 관리를 해주는 클래스 추가

## 📝  todo
- [ ] DI Container 관련 공부
- [ ] Factory Pattern 관련 정리
- [ ] DI 관리부 추가
