### ISSUE TITLE
[FEAT] 마니또 공개 뷰 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#62]
## 💡 Issue

마니또 공개 뷰를 구현합니다.

## 📝  todo
- [x] 마니또 공개 VC 생성
- [ ] 마니또 공개 Layout 잡기
- [ ] 타이포 애니메이션 구현
- [ ] 랜덤 애니메이션 구현
