### ISSUE TITLE
[ADD] 마니또 랜덤 돌리기 뷰 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#70]
## 💡 Issue

마니또 랜덤 돌리기 뷰를 구현합니다.

## 📝  todo
- [x] 레버 뷰 구현
- [x] 레버 스와이프 구현
- [x] 캡슐 열리는 뷰 구현
- [x] 이름 나오는 뷰 구현
- [ ] 확인 버튼 나타남 구현
