### ISSUE TITLE
[FEAT] 앱 플로우 연결하기

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#72]
## 💡 Issue

앱 플로우를 연결합니다.

## 📝  todo
- [x] 스플래시 -> 메인
- [x] 스플래시 -> 닉네임
- [x] 메인 -> 디테일wait
- [x] 메인 -> 디테일 ing
- [x] 디테일wait -> 마니또 선정 -> 디테일 ing
- [x] 디테일 ing -> 마니또 공개 -> 완료
- [x] 디테일 ing -> 쪽지함

**Comment by MMMIIIN** [comment]
도전 !
