### ISSUE TITLE
[CHORE] 색상변수 수정

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#86]
## 💡 Issue

- 불필요한 색상값들 삭제합니다.
- 색상 순서를 수정합니다.
- 꼭 필요한 withAlpha값이 아니면 주는 opacity가 100인 색상으로 분리합니다.

## 📝  todo
- [x] 불필요한 색상 삭제
- [x] 색상 순서에 따른 변수명 수정
- [x] 수정된 변수명 모든 view에 적용
- [x] withAlpha사용은 꼭 필요한 곳이 아니면 지양
