### ISSUE TITLE
[FEAT] 대기중 view 시작 날짜 지났을 때 flow 추가

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MC2-Team5-Firefighter#99]
## 💡 Issue

- 대기중 view에서 시작날짜가 지났을 때 alert과 함께 재설정 modal올라오게 설정

## 📝  todo
- [x] 시작,종료 날짜 하나의 변수로 연결하기
- [x] 날짜 지났을 때 alert 생성
- [x] 날짜 변경 안되면 시작 안되게 (alert 생성)
- [x] default: 오늘 날짜부터 설정 기간만큼 밀리게
